In [3]:
import numpy as np




no_of_resources=int(input("Enter no. of resources:"))
no_of_processes=int(input("Enter no. of processes:"))

total_resources=[]
print("Enter total no of resources:")
for i in range(no_of_resources):
    k=int(input("Enter {} :".format(i+1)))
    total_resources.append(k)
    
total_resources=np.array(total_resources)


# print(type(total_resources))

processes=[]
maximum_need=[]
current_allocation=[]
# remaing_need=[]
# current_available=[]

print("Resours entry should be in one row\n")
for i in range(no_of_processes):
    p=input("Enter process:")
    processes.append(p)
    max_need=input("Enter max need:").split(" ")
    max_need = list(map(int, max_need))
    maximum_need.append(max_need)
    curr_allo=input("Enter current allocation:").split(" ")
    curr_allo = list(map(int, curr_allo))
    current_allocation.append(curr_allo)
    
maximum_need=np.array(maximum_need)
maximum_need=maximum_need.reshape(no_of_processes,no_of_resources)

current_allocation=np.array(current_allocation)
current_allocation=current_allocation.reshape(no_of_processes,no_of_resources)


print("Total resources are:")
print(total_resources)
print("\nMaximum need matrix")
print(maximum_need)
print("\nCurrent allocation matrix")
print(current_allocation)
total_of_current_allocation=np.sum(current_allocation,axis=0)
print(total_of_current_allocation)



remaing_need=maximum_need-current_allocation
print("\nRemaing need matrix")
print(remaing_need)



current_available=np.zeros((no_of_processes+1,no_of_resources),dtype=int)
# print(current_available)

current_available[0]=total_resources-total_of_current_allocation
# print(current_available)

index_match=[]
safe_sequence=[]

for i in range(no_of_processes):
    f=0
    for j in range(no_of_processes):
        check=current_available[i]>=remaing_need[j]
        res=all(ele==True for ele in check)
        if res and j not in index_match:
            index_match.append(j)
            f=1
            break
    if f==0:
        print("Deadlock")
        break
    else:
        safe_sequence.append(processes[j])
        current_available[i+1]=current_available[i]+current_allocation[j]
    

print("\nSafe sequence is:")
print(safe_sequence)
print("\n Current available matrix:")
print(current_available)

Enter no. of resources:3
Enter no. of processes:3
Enter total no of resources:
Enter 1 :3
Enter 2 :3
Enter 3 :3
Resours entry should be in one row

Enter process:p1
Enter max need:2 2 2
Enter current allocation:0 0 1
Enter process:p2
Enter max need:2 2 2
Enter current allocation:0 1 0
Enter process:p3
Enter max need:2 2 2
Enter current allocation:1 0 0
Total resources are:
[3 3 3]

Maximum need matrix
[[2 2 2]
 [2 2 2]
 [2 2 2]]

Current allocation matrix
[[0 0 1]
 [0 1 0]
 [1 0 0]]
[1 1 1]

Remaing need matrix
[[2 2 1]
 [2 1 2]
 [1 2 2]]

Safe sequence is:
['p1', 'p2', 'p3']

 Current available matrix:
[[2 2 2]
 [2 2 3]
 [2 3 3]
 [3 3 3]]
